/*
    Project Euler - Problem 2
    Even Fibonacci Numbers

    Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
    By starting with  and , the first terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
    find the sum of the even-valued terms.
*/

#include <iostream>
using namespace std;


bool is_even(int number) {
    return (number & 1) == 0; // faster than %
}

int main() {
    const int limit = 4'000'000;

    long long sum = 0;

    int prev2 = 1;
    int prev1 = 2;

    while (prev1 <= limit) {
        if (is_even(prev1))
            sum += prev1;

        int next = prev1 + prev2;
        prev2 = prev1;
        prev1 = next;
    }

    std::cout << "Total sum of even Fibonacci terms: " << sum << '\n';
}

