/*
    Project Euler - Problem 2
    Even Fibonacci Numbers

    Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
    By starting with  and , the first terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
    find the sum of the even-valued terms.
*/

#include <iostream>
using namespace std;


bool is_even (int number) {
    return number % 2 == 0;
}

int main(int argc, char* argv[]) {
    cout << "Project Euler - Problem 2" << endl;
    cout << "-------------------------" << endl;

    const int limit = 4000000;

    int sum = 0;
    int prev_2 = 0;
    int prev = 1;
    int term = 1;

    while (term <= limit) {
        term = prev_2 + prev;
        prev_2 = prev;
        prev = term;

        if (is_even(term)) {
            sum += term;
        }

        cout << term << ", ";
    }

    cout << endl << "Total sum of even terms: " << sum << endl;

    return 0;
}    

