/*
    Project Euler - Problem 2
    Even Fibonacci Numbers

    Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
    By starting with  and , the first terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
    find the sum of the even-valued terms.
*/

#include <iostream>
using namespace std;


int main() {
    const int limit = 4'000'000;

    long long sum = 0;

    long long even_prev = 2;   // E1
    long long even_prev2 = 0;  // E0

    while (even_prev <= limit) {
        sum += even_prev;

        long long next_even = 4 * even_prev + even_prev2;
        even_prev2 = even_prev;
        even_prev = next_even;
    }

    std::cout << "Total sum of even Fibonacci terms: " << sum << std::endl;
}